spring:
  profiles:
    active: test
    include: enterprise

source:
    enabled: file

    file:
        location: /home/morlack/jiradata
report:
  dashboard:
    enabled: false
    url: http://localhost:8090
    token:
  file:
    enabled: true
    location: /Users/youritjang/Downloads/demo-project2/dump.json

filters:
    status: "To Do"

field-mapping:
    rank: "customfield_11400"
    feature:
        estimation: "customfield_11400"
        acceptanceCriteria: "customfield_10502"
    bug:
        reproductionPath: "customfield_13001"
        software: "customfield_13002"
        expectedBehavior: "customfield_13003"
        acceptationCriteria: "customfield_13004"

    epic:
        goal: "customfield_12001"


validation:
        backlog:
            rating-threshold: 0.6
            active: true
        feature:
            rating-threshold: 0.7
            active: true
        story:
            rating-threshold: 0.6
            active: true
            as-keywords: ["as a"]
            i-keywords: ["i want to"]
            so-keywords: ["so "]
        criteria:
            rating-threshold: 0.7
            active: true
            given-keywords: ["given"]
            when-keywords: ["when"]
            then-keywords: ["then"]
        estimation:
            rating-threshold: 0.7
            active: false
        bug:
            active: true
        epic:
            rating-threshold: 0.7
            active: false