spring:
  profiles:
    active: test
    include: enterprise

application:
    dataformat: jirajson
    inputfile: /Users/youritjang/Downloads/storynator
    status: "To Do"

fieldMapping:
    issue:
        rank: "customfield_10401"
        summary: "customfield_11400"
        estimation: "customfield_11400"

validation:
        backlog:
            ratingtreshold: 60.0
        issue:
            ratingtreshold: 0.7
        story:
            ratingtreshold: 0.6
            active: true
            asKeywords: ["as a"]
            iKeywords: ["i want to"]
            soKeywords: ["so "]
        bug:
            filledWith: ["","component"]
        criteria:
            fieldSource: "description#criteria"
            ratingtreshold: 0.7
            active: false
            givenKeywords: ["given"]
            whenKeywords: ["when"]
            thenKeywords: ["then"]
        estimation:
            ratingtreshold: 0.7
            active: false

dashboard:
  serviceUrl: http://localhost:8090
