spring:
  profiles:
    active: test
    include: enterprise

source:
    enabled: file

    file:
        location: /home/morlack/jiradata

filters:
    status: "To Do"

field-mapping:
    rank: "customfield_11400"
    feature:
        estimation: "customfield_11400"
        acceptanceCriteria: "customfield_10502"
    bug:
        reproductionPath: "customfield_13001"
        software: "customfield_13002"
        expectedBehavior: "customfield_13003"
        acceptationCriteria: "customfield_13004"

    epic:
        goal: "customfield_12001"


validation:
        backlog:
            ratingtreshold: 60.0
        issue:
            ratingtreshold: 0.7
        story:
            ratingtreshold: 0.6
            active: true
            asKeywords: ["as a"]
            iKeywords: ["i want to"]
            soKeywords: ["so "]
        bug:
            filledWith: ["","component"]
        criteria:
            ratingtreshold: 0.7
            active: false
            givenKeywords: ["given"]
            whenKeywords: ["when"]
            thenKeywords: ["then"]
        estimation:
            ratingtreshold: 0.7
            active: false