application:
    dataformat: jirajson
    inputfile:
    outputfile: "stories-output.json"
    url:
    authkey:
    projectkey:
    status: To Do

ranking:
    desiredMiniumStableRanking: 50
    desiredMinimumUnstableRanking: 50
    desiredRankingStrategy: Curved

validation:
        backlog:
            ratingtreshold: 60.0
        issue:
            ratingtreshold: 0.7
        story:
            ratingtreshold: 0.7
        criteria:
            ratingtreshold: 0.7
        estimation:
            ratingtreshold: 0.7
